application: mgimo-timetable
version: 1
runtime: python27
api_version: 1
threadsafe: yes
manual_scaling:
  instances: 1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /_ah/spi/.*
  script: api.APPLICATION

- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

builtins:
- deferred: on

libraries:
- name: webapp2
  version: "2.5.2"

- name: lxml
  version: "latest"

- name: endpoints
  version: latest